name: Release Windows x64

on:
  push:
    tags:
      - "v*"

jobs:
  build-release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: 'frontend/ui/pnpm-lock.yaml'
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc
      - uses: Swatinem/rust-cache@v2
      - name: Build JS
        working-directory: ./frontend/ui
        run: |
          pnpm install
          pnpm build
      - name: Build
        run: cargo build --release --target x86_64-pc-windows-msvc --bin gwenland
      - name: Upload to GH Releases
        uses: softprops/action-gh-release@v2
        with:
          files: target/x86_64-pc-windows-msvc/release/gwenland.exe
